/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gorest.test;

import com.gorest.controller.UsuarioController;
import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.builder.ResponseSpecBuilder;
import io.restassured.http.ContentType;
import org.junit.BeforeClass;


public class BaseTest {


    @BeforeClass
    public static void setup() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.baseURI = "https://gorest.co.in";
        RestAssured.basePath = "/public/v2";

       RestAssured.requestSpecification = new RequestSpecBuilder().setContentType(ContentType.JSON).build();

        RestAssured.responseSpecification = new ResponseSpecBuilder().expectContentType(ContentType.JSON).build();

    }
}
